-- Source: https://github.com/NvChad/base46
-- Theme: onedark; transparency: false; no user overrides.
-- Integrations: defaults, devicons, git, lsp, syntax, treesitter, leap, blink
-- Blink-only overrides: opaque dark floats and a blue selection; editor theme unchanged.
-- Original theme credits: https://github.com/one-dark
-- License notices: base46-LICENSE and base16-LICENSE in this directory.

vim.opt.termguicolors = true
vim.opt.background = "dark"
vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end
vim.g.colors_name = "vendored-onedark"

vim.g.terminal_color_0 = "#353b45"
vim.g.terminal_color_1 = "#e06c75"
vim.g.terminal_color_2 = "#98c379"
vim.g.terminal_color_3 = "#e5c07b"
vim.g.terminal_color_4 = "#61afef"
vim.g.terminal_color_5 = "#c678dd"
vim.g.terminal_color_6 = "#56b6c2"
vim.g.terminal_color_7 = "#abb2bf"
vim.g.terminal_color_8 = "#545862"
vim.g.terminal_color_9 = "#e06c75"
vim.g.terminal_color_10 = "#98c379"
vim.g.terminal_color_11 = "#e5c07b"
vim.g.terminal_color_12 = "#61afef"
vim.g.terminal_color_13 = "#c678dd"
vim.g.terminal_color_14 = "#56b6c2"
vim.g.terminal_color_15 = "#c8ccd4"

vim.api.nvim_set_hl(0, "@annotation", { fg = "#be5046" })
vim.api.nvim_set_hl(0, "@attribute", { fg = "#e5c07b" })
vim.api.nvim_set_hl(0, "@character", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "@comment", { fg = "#565c64" })
vim.api.nvim_set_hl(0, "@comment.danger", { bg = "#e06c75", fg = "#252931" })
vim.api.nvim_set_hl(0, "@comment.note", { bg = "#61afef", fg = "#1e222a" })
vim.api.nvim_set_hl(0, "@comment.todo", { bg = "#abb2bf", fg = "#42464e" })
vim.api.nvim_set_hl(0, "@comment.warning", { bg = "#d19a66", fg = "#252931" })
vim.api.nvim_set_hl(0, "@constant", { fg = "#d19a66" })
vim.api.nvim_set_hl(0, "@constant.builtin", { fg = "#d19a66" })
vim.api.nvim_set_hl(0, "@constant.macro", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "@constructor", { fg = "#56b6c2" })
vim.api.nvim_set_hl(0, "@definition", { sp = "#565c64", underline = true })
vim.api.nvim_set_hl(0, "@diff.delta", { fg = "#6f737b" })
vim.api.nvim_set_hl(0, "@diff.minus", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "@diff.plus", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "@error", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "@function", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "@function.builtin", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "@function.call", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "@function.macro", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "@function.method", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "@function.method.call", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "@keyword", { fg = "#c678dd" })
vim.api.nvim_set_hl(0, "@keyword.conditional", { fg = "#c678dd" })
vim.api.nvim_set_hl(0, "@keyword.conditional.ternary", { fg = "#c678dd" })
vim.api.nvim_set_hl(0, "@keyword.directive", { fg = "#e5c07b" })
vim.api.nvim_set_hl(0, "@keyword.directive.define", { fg = "#c678dd" })
vim.api.nvim_set_hl(0, "@keyword.exception", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "@keyword.function", { fg = "#c678dd" })
vim.api.nvim_set_hl(0, "@keyword.import", { link = "Include" })
vim.api.nvim_set_hl(0, "@keyword.operator", { fg = "#c678dd" })
vim.api.nvim_set_hl(0, "@keyword.repeat", { fg = "#e5c07b" })
vim.api.nvim_set_hl(0, "@keyword.return", { fg = "#c678dd" })
vim.api.nvim_set_hl(0, "@keyword.storage", { fg = "#e5c07b" })
vim.api.nvim_set_hl(0, "@markup.heading", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "@markup.italic", { italic = true })
vim.api.nvim_set_hl(0, "@markup.link", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "@markup.link.label", { fg = "#56b6c2" })
vim.api.nvim_set_hl(0, "@markup.link.url", { fg = "#d19a66", underline = true })
vim.api.nvim_set_hl(0, "@markup.list", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "@markup.quote", { bg = "#252931" })
vim.api.nvim_set_hl(0, "@markup.raw", { fg = "#d19a66" })
vim.api.nvim_set_hl(0, "@markup.strikethrough", { strikethrough = true })
vim.api.nvim_set_hl(0, "@markup.strong", { bold = true })
vim.api.nvim_set_hl(0, "@markup.underline", { underline = true })
vim.api.nvim_set_hl(0, "@module", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "@number", { fg = "#d19a66" })
vim.api.nvim_set_hl(0, "@number.float", { fg = "#d19a66" })
vim.api.nvim_set_hl(0, "@operator", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "@property", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "@punctuation.bracket", { fg = "#be5046" })
vim.api.nvim_set_hl(0, "@punctuation.delimiter", { fg = "#be5046" })
vim.api.nvim_set_hl(0, "@reference", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "@scope", { bold = true })
vim.api.nvim_set_hl(0, "@string", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "@string.escape", { fg = "#56b6c2" })
vim.api.nvim_set_hl(0, "@string.regex", { fg = "#56b6c2" })
vim.api.nvim_set_hl(0, "@symbol", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "@tag", { fg = "#e5c07b" })
vim.api.nvim_set_hl(0, "@tag.attribute", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "@tag.delimiter", { fg = "#be5046" })
vim.api.nvim_set_hl(0, "@text", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "@text.emphasis", { fg = "#d19a66" })
vim.api.nvim_set_hl(0, "@text.strike", { fg = "#be5046", strikethrough = true })
vim.api.nvim_set_hl(0, "@type.builtin", { fg = "#e5c07b" })
vim.api.nvim_set_hl(0, "@variable", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "@variable.builtin", { fg = "#d19a66" })
vim.api.nvim_set_hl(0, "@variable.member", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "@variable.member.key", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "@variable.parameter", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "Added", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "Boolean", { fg = "#d19a66" })

-- Blink integration: NvChad/base46@7df2bd89295db00b649cbc49bdf6fe5a1cc5df3b
-- Based on integrations/blink.lua with OneDark; float colors match the completion reference.
vim.api.nvim_set_hl(0, "BlinkCmpDoc", { bg = "#1e222a", fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "BlinkCmpDocBorder", { bg = "#1e222a", fg = "#565c64" })
vim.api.nvim_set_hl(0, "BlinkCmpDocCursorLine", { bg = "#282c34" })
vim.api.nvim_set_hl(0, "BlinkCmpDocSeparator", { fg = "#42464e" })
vim.api.nvim_set_hl(0, "BlinkCmpGhostText", { fg = "#565c64" })
vim.api.nvim_set_hl(0, "BlinkCmpKindClass", { fg = "#519ABA" })
vim.api.nvim_set_hl(0, "BlinkCmpKindCodeium", { fg = "#7eca9c" })
vim.api.nvim_set_hl(0, "BlinkCmpKindColor", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "BlinkCmpKindConstant", { fg = "#d19a66" })
vim.api.nvim_set_hl(0, "BlinkCmpKindConstructor", { fg = "#56b6c2" })
vim.api.nvim_set_hl(0, "BlinkCmpKindCopilot", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "BlinkCmpKindEnum", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "BlinkCmpKindEnumMember", { fg = "#de98fd" })
vim.api.nvim_set_hl(0, "BlinkCmpKindEvent", { fg = "#e7c787" })
vim.api.nvim_set_hl(0, "BlinkCmpKindField", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "BlinkCmpKindFile", { fg = "#c8ccd4" })
vim.api.nvim_set_hl(0, "BlinkCmpKindFolder", { fg = "#c8ccd4" })
vim.api.nvim_set_hl(0, "BlinkCmpKindFunction", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "BlinkCmpKindIdentifier", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "BlinkCmpKindInterface", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "BlinkCmpKindKeyword", { fg = "#c678dd" })
vim.api.nvim_set_hl(0, "BlinkCmpKindMethod", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "BlinkCmpKindModule", { fg = "#e5c07b" })
vim.api.nvim_set_hl(0, "BlinkCmpKindOperator", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "BlinkCmpKindProperty", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "BlinkCmpKindReference", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "BlinkCmpKindSnippet", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "BlinkCmpKindStruct", { fg = "#c678dd" })
vim.api.nvim_set_hl(0, "BlinkCmpKindStructure", { fg = "#c678dd" })
vim.api.nvim_set_hl(0, "BlinkCmpKindSuperMaven", { fg = "#e7c787" })
vim.api.nvim_set_hl(0, "BlinkCmpKindTabNine", { fg = "#DE8C92" })
vim.api.nvim_set_hl(0, "BlinkCmpKindText", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "BlinkCmpKindType", { fg = "#e5c07b" })
vim.api.nvim_set_hl(0, "BlinkCmpKindTypeParameter", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "BlinkCmpKindUnit", { fg = "#c678dd" })
vim.api.nvim_set_hl(0, "BlinkCmpKindValue", { fg = "#a3b8ef" })
vim.api.nvim_set_hl(0, "BlinkCmpKindVariable", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "BlinkCmpLabel", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "BlinkCmpLabelDeprecated", { fg = "#e06c75", strikethrough = true })
vim.api.nvim_set_hl(0, "BlinkCmpLabelDescription", { fg = "#6f737b" })
vim.api.nvim_set_hl(0, "BlinkCmpLabelDetail", { fg = "#6f737b" })
vim.api.nvim_set_hl(0, "BlinkCmpLabelMatch", { bold = true, fg = "#61afef" })
vim.api.nvim_set_hl(0, "BlinkCmpMenu", { bg = "#1e222a", fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "BlinkCmpMenuBorder", { bg = "#1e222a", fg = "#565c64" })
vim.api.nvim_set_hl(0, "BlinkCmpMenuSelection", { bg = "#61afef", fg = "#1e222a" })
vim.api.nvim_set_hl(0, "BlinkCmpScrollBarGutter", { bg = "#252931" })
vim.api.nvim_set_hl(0, "BlinkCmpScrollBarThumb", { bg = "#42464e" })
vim.api.nvim_set_hl(0, "BlinkCmpSignatureHelp", { bg = "NONE", fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "BlinkCmpSignatureHelpActiveParameter", { bold = true, fg = "#61afef" })
vim.api.nvim_set_hl(0, "BlinkCmpSignatureHelpBorder", { fg = "#565c64" })
vim.api.nvim_set_hl(0, "BlinkCmpSource", { fg = "#565c64" })

vim.api.nvim_set_hl(0, "Changed", { fg = "#e7c787" })
vim.api.nvim_set_hl(0, "Character", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "ColorColumn", { bg = "#252931" })
vim.api.nvim_set_hl(0, "Comment", { fg = "#565c64" })
vim.api.nvim_set_hl(0, "Conceal", { bg = "NONE" })
vim.api.nvim_set_hl(0, "Conditional", { fg = "#c678dd" })
vim.api.nvim_set_hl(0, "Constant", { fg = "#d19a66" })
vim.api.nvim_set_hl(0, "Cursor", { bg = "#abb2bf", fg = "#1e222a" })
vim.api.nvim_set_hl(0, "CursorColumn", { bg = "#353b45" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#252931" })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "Debug", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "Define", { fg = "#c678dd", sp = "none" })
vim.api.nvim_set_hl(0, "Delimiter", { fg = "#be5046" })
vim.api.nvim_set_hl(0, "DevIconDart", { fg = "#a3b8ef" })
vim.api.nvim_set_hl(0, "DevIconDefault", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "DevIconDockerfile", { fg = "#a3b8ef" })
vim.api.nvim_set_hl(0, "DevIconJSX", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "DevIconJava", { fg = "#fca2aa" })
vim.api.nvim_set_hl(0, "DevIconMd", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "DevIconSvelte", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "DevIconTSX", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "DevIconZig", { fg = "#fca2aa" })
vim.api.nvim_set_hl(0, "DevIconc", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "DevIconcss", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "DevIcondeb", { fg = "#a3b8ef" })
vim.api.nvim_set_hl(0, "DevIconhtml", { fg = "#DE8C92" })
vim.api.nvim_set_hl(0, "DevIconjpeg", { fg = "#c882e7" })
vim.api.nvim_set_hl(0, "DevIconjpg", { fg = "#c882e7" })
vim.api.nvim_set_hl(0, "DevIconjs", { fg = "#EBCB8B" })
vim.api.nvim_set_hl(0, "DevIconkt", { fg = "#fca2aa" })
vim.api.nvim_set_hl(0, "DevIconlock", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "DevIconlua", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "DevIconmp3", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "DevIconmp4", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "DevIconout", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "DevIconpng", { fg = "#c882e7" })
vim.api.nvim_set_hl(0, "DevIconpy", { fg = "#a3b8ef" })
vim.api.nvim_set_hl(0, "DevIconrb", { fg = "#ff75a0" })
vim.api.nvim_set_hl(0, "DevIconrpm", { fg = "#fca2aa" })
vim.api.nvim_set_hl(0, "DevIcontoml", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "DevIconts", { fg = "#519ABA" })
vim.api.nvim_set_hl(0, "DevIconttf", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "DevIconvue", { fg = "#7eca9c" })
vim.api.nvim_set_hl(0, "DevIconwoff", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "DevIconwoff2", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "DevIconxz", { fg = "#EBCB8B" })
vim.api.nvim_set_hl(0, "DevIconzip", { fg = "#EBCB8B" })
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = "#de98fd" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#e7c787" })
vim.api.nvim_set_hl(0, "DiffAdd", { bg = "#2a3231", fg = "#98c379" })
vim.api.nvim_set_hl(0, "DiffAdded", { bg = "#2a3231", fg = "#98c379" })
vim.api.nvim_set_hl(0, "DiffChange", { bg = "#262a32", fg = "#6f737b" })
vim.api.nvim_set_hl(0, "DiffChangeDelete", { bg = "#312931", fg = "#e06c75" })
vim.api.nvim_set_hl(0, "DiffDelete", { bg = "#312931", fg = "#e06c75" })
vim.api.nvim_set_hl(0, "DiffModified", { bg = "#342e36", fg = "#fca2aa" })
vim.api.nvim_set_hl(0, "DiffRemoved", { bg = "#312931", fg = "#e06c75" })
vim.api.nvim_set_hl(0, "DiffText", { bg = "#252931", fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "Directory", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "Error", { bg = "#e06c75", fg = "#1e222a" })
vim.api.nvim_set_hl(0, "ErrorMsg", { bg = "#1e222a", fg = "#e06c75" })
vim.api.nvim_set_hl(0, "Exception", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "Float", { fg = "#d19a66" })
vim.api.nvim_set_hl(0, "FloatBorder", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "FloatTitle", { bg = "#42464e", fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "FoldColumn", { bg = "none", fg = "#be5046" })
vim.api.nvim_set_hl(0, "Folded", { bg = "#252931", fg = "#6f737b" })
vim.api.nvim_set_hl(0, "Function", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "Identifier", { fg = "#e06c75", sp = "none" })
vim.api.nvim_set_hl(0, "IncSearch", { bg = "#d19a66", fg = "#353b45" })
vim.api.nvim_set_hl(0, "Include", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "Keyword", { fg = "#c678dd" })
vim.api.nvim_set_hl(0, "Label", { fg = "#e5c07b" })
vim.api.nvim_set_hl(0, "LazyButton", { bg = "#282c34", fg = "#888c94" })
vim.api.nvim_set_hl(0, "LazyCommit", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "LazyCommitIssue", { fg = "#ff75a0" })
vim.api.nvim_set_hl(0, "LazyDir", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "LazyH1", { bg = "#98c379", fg = "#1e222a" })
vim.api.nvim_set_hl(0, "LazyH2", { bold = true, fg = "#e06c75", underline = true })
vim.api.nvim_set_hl(0, "LazyNoCond", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "LazyOperator", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "LazyProgressDone", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "LazyReasonCmd", { fg = "#EBCB8B" })
vim.api.nvim_set_hl(0, "LazyReasonEvent", { fg = "#e7c787" })
vim.api.nvim_set_hl(0, "LazyReasonFt", { fg = "#de98fd" })
vim.api.nvim_set_hl(0, "LazyReasonImport", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "LazyReasonKeys", { fg = "#519ABA" })
vim.api.nvim_set_hl(0, "LazyReasonPlugin", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "LazyReasonRuntime", { fg = "#81A1C1" })
vim.api.nvim_set_hl(0, "LazyReasonSource", { fg = "#a3b8ef" })
vim.api.nvim_set_hl(0, "LazyReasonStart", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "LazySpecial", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "LazyTaskOutput", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "LazyUrl", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "LazyValue", { fg = "#519ABA" })
vim.api.nvim_set_hl(0, "LeapBackdrop", { fg = "#565c64" })
vim.api.nvim_set_hl(0, "LeapLabel", { bold = true, fg = "#e7c787" })
vim.api.nvim_set_hl(0, "LeapMatch", { bold = true, fg = "#e7c787" })
vim.api.nvim_set_hl(0, "LineNr", { fg = "#42464e" })
vim.api.nvim_set_hl(0, "LspInlayHint", { bg = "#252931", fg = "#6f737b" })
vim.api.nvim_set_hl(0, "LspReferenceRead", { bg = "#373b43" })
vim.api.nvim_set_hl(0, "LspReferenceText", { bg = "#373b43" })
vim.api.nvim_set_hl(0, "LspReferenceWrite", { bg = "#373b43" })
vim.api.nvim_set_hl(0, "LspSignatureActiveParameter", { bg = "#98c379", fg = "#1e222a" })
vim.api.nvim_set_hl(0, "Macro", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "MatchParen", { link = "MatchWord" })
vim.api.nvim_set_hl(0, "MatchWord", { bg = "#42464e", fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "ModeMsg", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "MoreMsg", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "NonText", { fg = "#545862" })
vim.api.nvim_set_hl(0, "Normal", { bg = "#1e222a", fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = "#1b1f27" })
vim.api.nvim_set_hl(0, "Number", { fg = "#d19a66" })
vim.api.nvim_set_hl(0, "NvDashAscii", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "NvDashButtons", { fg = "#6f737b" })
vim.api.nvim_set_hl(0, "NvDashFooter", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "NvimInternalError", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "Operator", { fg = "#abb2bf", sp = "none" })
vim.api.nvim_set_hl(0, "Pmenu", { bg = "#282c34" })
vim.api.nvim_set_hl(0, "PmenuSbar", { bg = "#282c34" })
vim.api.nvim_set_hl(0, "PmenuSel", { bg = "#61afef", fg = "#1e222a" })
vim.api.nvim_set_hl(0, "PmenuThumb", { bg = "#42464e" })
vim.api.nvim_set_hl(0, "PreProc", { fg = "#e5c07b" })
vim.api.nvim_set_hl(0, "Question", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "QuickFixLine", { bg = "#353b45" })
vim.api.nvim_set_hl(0, "Removed", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "Repeat", { fg = "#e5c07b" })
vim.api.nvim_set_hl(0, "Search", { bg = "#e5c07b", fg = "#353b45" })
vim.api.nvim_set_hl(0, "SignColumn", { fg = "#545862" })
vim.api.nvim_set_hl(0, "Special", { fg = "#56b6c2" })
vim.api.nvim_set_hl(0, "SpecialChar", { fg = "#be5046" })
vim.api.nvim_set_hl(0, "SpecialKey", { fg = "#545862" })
vim.api.nvim_set_hl(0, "Statement", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "StorageClass", { fg = "#e5c07b" })
vim.api.nvim_set_hl(0, "String", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "Structure", { fg = "#c678dd" })
vim.api.nvim_set_hl(0, "Substitute", { bg = "#e5c07b", fg = "#353b45" })
vim.api.nvim_set_hl(0, "Tag", { fg = "#e5c07b" })
vim.api.nvim_set_hl(0, "Title", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "Todo", { bg = "#353b45", fg = "#e5c07b" })
vim.api.nvim_set_hl(0, "TooLong", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "Type", { fg = "#e5c07b", sp = "none" })
vim.api.nvim_set_hl(0, "Typedef", { fg = "#e5c07b" })
vim.api.nvim_set_hl(0, "Variable", { fg = "#abb2bf" })
vim.api.nvim_set_hl(0, "Visual", { bg = "#3e4451" })
vim.api.nvim_set_hl(0, "VisualNOS", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "WarningMsg", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "WildMenu", { bg = "#e5c07b", fg = "#e06c75" })
vim.api.nvim_set_hl(0, "WinBar", { bg = "NONE" })
vim.api.nvim_set_hl(0, "WinBarNC", { bg = "NONE" })
vim.api.nvim_set_hl(0, "WinSeparator", { fg = "#31353d" })
vim.api.nvim_set_hl(0, "diffNewFile", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "diffOldFile", { fg = "#DE8C92" })
vim.api.nvim_set_hl(0, "gitcommitBranch", { bold = true, fg = "#d19a66" })
vim.api.nvim_set_hl(0, "gitcommitComment", { fg = "#545862" })
vim.api.nvim_set_hl(0, "gitcommitDiscarded", { fg = "#545862" })
vim.api.nvim_set_hl(0, "gitcommitDiscardedFile", { bold = true, fg = "#e06c75" })
vim.api.nvim_set_hl(0, "gitcommitDiscardedType", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "gitcommitHeader", { fg = "#c678dd" })
vim.api.nvim_set_hl(0, "gitcommitOverflow", { fg = "#e06c75" })
vim.api.nvim_set_hl(0, "gitcommitSelected", { fg = "#545862" })
vim.api.nvim_set_hl(0, "gitcommitSelectedFile", { bold = true, fg = "#98c379" })
vim.api.nvim_set_hl(0, "gitcommitSelectedType", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "gitcommitSummary", { fg = "#98c379" })
vim.api.nvim_set_hl(0, "gitcommitUnmergedFile", { bold = true, fg = "#e06c75" })
vim.api.nvim_set_hl(0, "gitcommitUnmergedType", { fg = "#61afef" })
vim.api.nvim_set_hl(0, "gitcommitUntracked", { fg = "#545862" })
vim.api.nvim_set_hl(0, "gitcommitUntrackedFile", { fg = "#e5c07b" })
vim.api.nvim_set_hl(0, "healthSuccess", { bg = "#98c379", fg = "#1e222a" })
